"""add_location_and_property_reports

Revision ID: 000ce5a4f342
Revises: 36e6dca7db30
Create Date: 2026-07-29 23:08:08.044356
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "000ce5a4f342"
down_revision: Union[str, None] = "36e6dca7db30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_data",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("google_map_url", sa.String(length=1000), nullable=True),
        sa.Column("is_important", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_location_data_id"), "location_data", ["id"], unique=False)
    op.create_table(
        "property_reports",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("reporter_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="pending | resolved | dismissed",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_property_reports_id"), "property_reports", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_property_reports_property_id"),
        "property_reports",
        ["property_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_property_reports_reporter_id"),
        "property_reports",
        ["reporter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_property_reports_status"), "property_reports", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_property_reports_status"), table_name="property_reports")
    op.drop_index(
        op.f("ix_property_reports_reporter_id"), table_name="property_reports"
    )
    op.drop_index(
        op.f("ix_property_reports_property_id"), table_name="property_reports"
    )
    op.drop_index(op.f("ix_property_reports_id"), table_name="property_reports")
    op.drop_table("property_reports")
    op.drop_index(op.f("ix_location_data_id"), table_name="location_data")
    op.drop_table("location_data")
    # ### end Alembic commands ###
