"""add_image_url_to_location_data

Revision ID: 0e9b5bc22bce
Revises: 41303fcdd94e
Create Date: 2026-07-31 18:41:02.728758
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9b5bc22bce'
down_revision: Union[str, None] = '41303fcdd94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_data', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location_data', 'image_url')
    # ### end Alembic commands ###
