"""change preference_type to string

Revision ID: 11acaaacb974
Revises: a03544f771e5
Create Date: 2026-07-14 18:31:33.884071
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "11acaaacb974"
down_revision: Union[str, None] = "a03544f771e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "preference_type",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=sa.String(length=255),
        postgresql_using="array_to_string(preference_type, ',')",
        comment="e.g. 'residential'",
        existing_comment="e.g. ['residential', 'commercial']",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "preference_type",
        existing_type=sa.String(length=255),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        postgresql_using="string_to_array(preference_type, ',')",
        comment="e.g. ['residential', 'commercial']",
        existing_comment="e.g. 'residential'",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
