"""add_image_url_to_property_types

Revision ID: 1df743668921
Revises: 9eb94ef564ce
Create Date: 2026-08-01 02:48:14.053494
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1df743668921"
down_revision: Union[str, None] = "9eb94ef564ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "property_types", sa.Column("image_url", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "verification_status",
        existing_type=sa.VARCHAR(length=20),
        comment="pending | verified | rejected",
        existing_comment="unverified | review_request | verified | rejected",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "auth_provider_uid",
        existing_type=sa.VARCHAR(length=256),
        comment="Firebase UID or Supabase UUID",
        existing_comment="Firebase UID or Supabase UUID (legacy/optional)",
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_testimonials_status"), "testimonials", ["status"], unique=False
    )
    op.alter_column(
        "testimonials",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="False for soft deleted",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "testimonials",
        "status",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="pending, approved, rejected",
        existing_nullable=False,
    )
    op.alter_column(
        "testimonials",
        "rating",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="1-5",
        existing_nullable=True,
    )
    op.alter_column(
        "testimonials",
        "avatar_key",
        existing_type=sa.VARCHAR(length=500),
        comment=None,
        existing_comment="R2 object key",
        existing_nullable=True,
    )
    op.alter_column(
        "testimonials",
        "content",
        existing_type=sa.String(length=300),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "testimonials",
        "author_role",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="owner, seeker, agency",
        existing_nullable=False,
        existing_server_default=sa.text("'seeker'::character varying"),
    )
    op.drop_column("property_types", "image_url")
    op.alter_column(
        "properties",
        "is_featured",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "otp_records",
        "hashed_otp",
        existing_type=sa.VARCHAR(length=256),
        comment="bcrypt hash of the 6-digit OTP",
        existing_comment="HMAC-SHA256 hash of the 6-digit OTP",
        existing_nullable=False,
    )
    op.alter_column(
        "otp_records",
        "phone",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Target phone number (E.164 format preferred)",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_limit_overrides_id"), table_name="limit_overrides")
    op.create_index(
        op.f("ix_limit_overrides_created_at"),
        "limit_overrides",
        ["created_at"],
        unique=False,
    )
    op.alter_column(
        "limit_overrides",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "limit_overrides",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "limit_overrides",
        "payment_ref",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.create_table(
        "chat_sessions_memory",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "session_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "message",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chat_sessions_memory_pkey")),
    )
    op.create_index(
        op.f("idx_chat_sessions_memory_session_id"),
        "chat_sessions_memory",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "phone_number", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "property_code", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.Column(
            "session_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=32),
            server_default=sa.text("'open'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("outcome", sa.VARCHAR(length=32), autoincrement=False, nullable=True),
        sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chat_sessions_pkey")),
        sa.UniqueConstraint(
            "session_id",
            name=op.f("chat_sessions_session_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_chat_sessions_phone_status"),
        "chat_sessions",
        ["phone_number", "status"],
        unique=False,
    )
    # ### end Alembic commands ###
