"""phone_auth_nullable_email_unique_phone

Revision ID: 55a48a0834f8
Revises: a64ea2ad0914
Create Date: 2026-07-29 19:47:00.950210
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a48a0834f8'
down_revision: Union[str, None] = 'a64ea2ad0914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add phone as nullable first (existing rows may exist)
    op.add_column('otp_records', sa.Column('phone', sa.String(length=20), nullable=True, comment='Target phone number (E.164 format preferred)'))
    # Clear out any old OTP records (they have email, not phone — all invalid now)
    op.execute("DELETE FROM otp_records")
    # Now make phone NOT NULL
    op.alter_column('otp_records', 'phone', nullable=False)

    op.alter_column('otp_records', 'hashed_otp',
               existing_type=sa.VARCHAR(length=256),
               comment='HMAC-SHA256 hash of the 6-digit OTP',
               existing_comment='bcrypt hash of the 6-digit OTP',
               existing_nullable=False)
    op.drop_index(op.f('ix_otp_records_email'), table_name='otp_records')
    op.create_index(op.f('ix_otp_records_phone'), 'otp_records', ['phone'], unique=False)
    op.drop_column('otp_records', 'email')

    op.alter_column('users', 'auth_provider_uid',
               existing_type=sa.VARCHAR(length=256),
               nullable=True,
               comment='Firebase UID or Supabase UUID (legacy/optional)',
               existing_comment='Firebase UID or Supabase UUID')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('users', 'auth_provider_uid',
               existing_type=sa.VARCHAR(length=256),
               nullable=False,
               comment='Firebase UID or Supabase UUID',
               existing_comment='Firebase UID or Supabase UUID (legacy/optional)')
    op.add_column('otp_records', sa.Column('email', sa.VARCHAR(length=256), autoincrement=False, nullable=False, comment='Target email address'))
    op.drop_index(op.f('ix_otp_records_phone'), table_name='otp_records')
    op.create_index(op.f('ix_otp_records_email'), 'otp_records', ['email'], unique=False)
    op.alter_column('otp_records', 'hashed_otp',
               existing_type=sa.VARCHAR(length=256),
               comment='bcrypt hash of the 6-digit OTP',
               existing_comment='HMAC-SHA256 hash of the 6-digit OTP',
               existing_nullable=False)
    op.drop_column('otp_records', 'phone')
    # ### end Alembic commands ###
