"""add video_link to property

Revision ID: 7ca286b7445d
Revises: e7d0dbbc8e8e
Create Date: 2026-07-16 14:49:43.824278
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7ca286b7445d"
down_revision: Union[str, None] = "e7d0dbbc8e8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "properties",
        sa.Column(
            "video_link",
            sa.String(length=1000),
            nullable=True,
            comment="Direct URL or iframe embed code",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "video_link")
    # ### end Alembic commands ###
