"""add_agency_banner_key

Revision ID: 9eb94ef564ce
Revises: 0e9b5bc22bce
Create Date: 2026-07-31 19:37:59.082817
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9eb94ef564ce"
down_revision: Union[str, None] = "0e9b5bc22bce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agency_profiles", sa.Column("banner_key", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agency_profiles", "banner_key")
    # ### end Alembic commands ###
