"""add_otp_records

Revision ID: a03544f771e5
Revises: ec9fc2f8260a
Create Date: 2026-07-13 22:49:27.518680
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03544f771e5'
down_revision: Union[str, None] = 'ec9fc2f8260a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_records',
    sa.Column('email', sa.String(length=256), nullable=False, comment='Target email address'),
    sa.Column('hashed_otp', sa.String(length=256), nullable=False, comment='bcrypt hash of the 6-digit OTP'),
    sa.Column('purpose', sa.String(length=20), nullable=False, comment='login | registration'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='OTP expiry timestamp'),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_records_email'), 'otp_records', ['email'], unique=False)
    op.create_index(op.f('ix_otp_records_id'), 'otp_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_records_id'), table_name='otp_records')
    op.drop_index(op.f('ix_otp_records_email'), table_name='otp_records')
    op.drop_table('otp_records')
    # ### end Alembic commands ###
