"""Add testimonials

Revision ID: a64ea2ad0914
Revises: 3d4cadbd5a57
Create Date: 2026-07-29 17:09:13.817365
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a64ea2ad0914'
down_revision: Union[str, None] = '3d4cadbd5a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('limit_overrides', 'payment_ref',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('limit_overrides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_limit_overrides_created_at'), table_name='limit_overrides')
    op.create_index(op.f('ix_limit_overrides_id'), 'limit_overrides', ['id'], unique=False)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.add_column('testimonials', sa.Column('author_name', sa.String(length=100), nullable=False))
    op.add_column('testimonials', sa.Column('author_role', sa.String(length=50), nullable=False, comment='owner, seeker, agency'))
    op.add_column('testimonials', sa.Column('author_location', sa.String(length=200), nullable=True))
    op.add_column('testimonials', sa.Column('avatar_key', sa.String(length=500), nullable=True, comment='R2 object key'))
    op.add_column('testimonials', sa.Column('rating', sa.Integer(), nullable=True, comment='1-5'))
    op.add_column('testimonials', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('testimonials', sa.Column('is_active', sa.Boolean(), nullable=False, comment='False for soft deleted'))
    op.alter_column('testimonials', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('testimonials', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               comment='pending, approved, rejected',
               existing_nullable=False)
    op.drop_index(op.f('ix_testimonials_status'), table_name='testimonials')
    op.drop_column('testimonials', 'photo_key')
    op.drop_column('testimonials', 'role')
    op.drop_column('testimonials', 'name')
    op.alter_column('users', 'verification_status',
               existing_type=sa.VARCHAR(length=20),
               comment='unverified | review_request | verified | rejected',
               existing_comment='pending | verified | rejected',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verification_status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending | verified | rejected',
               existing_comment='unverified | review_request | verified | rejected',
               existing_nullable=False)
    op.add_column('testimonials', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('testimonials', sa.Column('role', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('testimonials', sa.Column('photo_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_testimonials_status'), 'testimonials', ['status'], unique=False)
    op.alter_column('testimonials', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, approved, rejected',
               existing_nullable=False)
    op.alter_column('testimonials', 'content',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('testimonials', 'is_active')
    op.drop_column('testimonials', 'is_featured')
    op.drop_column('testimonials', 'rating')
    op.drop_column('testimonials', 'avatar_key')
    op.drop_column('testimonials', 'author_location')
    op.drop_column('testimonials', 'author_role')
    op.drop_column('testimonials', 'author_name')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.alter_column('reviews', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_limit_overrides_id'), table_name='limit_overrides')
    op.create_index(op.f('ix_limit_overrides_created_at'), 'limit_overrides', ['created_at'], unique=False)
    op.alter_column('limit_overrides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('limit_overrides', 'payment_ref',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
