"""add extra_details to property

Revision ID: ac52ee65b660
Revises: 7ca286b7445d
Create Date: 2026-07-16 14:52:36.719848
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac52ee65b660'
down_revision: Union[str, None] = '7ca286b7445d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('extra_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible field for PG sharing, vacancies, etc.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'extra_details')
    # ### end Alembic commands ###
