"""update_property_model

Revision ID: e7d0dbbc8e8e
Revises: 4a259267278f
Create Date: 2026-07-15 21:24:26.528503
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7d0dbbc8e8e"
down_revision: Union[str, None] = "4a259267278f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "properties", sa.Column("area", sa.Integer(), nullable=True, comment="sq ft")
    )
    op.add_column("properties", sa.Column("bedrooms", sa.Integer(), nullable=True))
    op.add_column("properties", sa.Column("bathrooms", sa.Integer(), nullable=True))
    op.add_column(
        "properties",
        sa.Column(
            "furnishing",
            sa.String(length=20),
            nullable=True,
            comment="unfurnished | semi | furnished",
        ),
    )
    op.add_column(
        "properties",
        sa.Column(
            "price_unit",
            sa.String(length=20),
            nullable=False,
            comment="per_month | total",
        ),
    )
    op.add_column("properties", sa.Column("location_address", sa.Text(), nullable=True))
    op.add_column(
        "properties", sa.Column("location_state", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "properties", sa.Column("owner_whatsapp", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "properties", sa.Column("admin_reviewed_by", sa.UUID(), nullable=True)
    )
    op.add_column(
        "properties",
        sa.Column("admin_reviewed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "properties", sa.Column("admin_review_reason", sa.Text(), nullable=True)
    )
    op.add_column(
        "properties",
        sa.Column(
            "availability_confirmed_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "properties",
        sa.Column("availability_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column("properties", "description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "properties",
        "enquiry_type",
        existing_type=sa.VARCHAR(length=20),
        comment="whatsapp_bot | manual_chat",
        existing_comment="whatsapp (pg/hostel) | chat (others)",
        existing_nullable=False,
    )
    op.alter_column(
        "properties",
        "location_pincode",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.create_foreign_key(
        None, "properties", "users", ["admin_reviewed_by"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("properties", "review_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "properties",
        sa.Column(
            "review_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "properties", type_="foreignkey")
    op.alter_column(
        "properties",
        "location_pincode",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.alter_column(
        "properties",
        "enquiry_type",
        existing_type=sa.VARCHAR(length=20),
        comment="whatsapp (pg/hostel) | chat (others)",
        existing_comment="whatsapp_bot | manual_chat",
        existing_nullable=False,
    )
    op.alter_column(
        "properties", "description", existing_type=sa.TEXT(), nullable=False
    )
    op.drop_column("properties", "availability_expires_at")
    op.drop_column("properties", "availability_confirmed_at")
    op.drop_column("properties", "admin_review_reason")
    op.drop_column("properties", "admin_reviewed_at")
    op.drop_column("properties", "admin_reviewed_by")
    op.drop_column("properties", "owner_whatsapp")
    op.drop_column("properties", "location_state")
    op.drop_column("properties", "location_address")
    op.drop_column("properties", "price_unit")
    op.drop_column("properties", "furnishing")
    op.drop_column("properties", "bathrooms")
    op.drop_column("properties", "bedrooms")
    op.drop_column("properties", "area")
    # ### end Alembic commands ###
