"""add_user_id_to_reviews

Revision ID: f20c6fef8f58
Revises: a805a377ae06
Create Date: 2026-07-20 16:20:42.552814
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20c6fef8f58'
down_revision: Union[str, None] = 'a805a377ae06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###
